// <auto-generated />
using HAOS.Models.Training;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HAOS_API.Migrations
{
    [DbContext(typeof(TrainingDb))]
    [Migration("20250625134345_CircuitAndWorkoutDescriptions")]
    partial class CircuitAndWorkoutDescriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HAOS.Models.Training.Circuit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("ProgramDayId")
                        .HasColumnType("int");

                    b.Property<int>("Rounds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProgramDayId");

                    b.ToTable("CircuitData");
                });

            modelBuilder.Entity("HAOS.Models.Training.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DemoUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ExerciseData");
                });

            modelBuilder.Entity("HAOS.Models.Training.ProgramDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProgramSegmentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<int>("WeekNum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProgramSegmentId");

                    b.ToTable("ProgramDayData");
                });

            modelBuilder.Entity("HAOS.Models.Training.ProgramSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Subtitle")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<int?>("TrainingProgramId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainingProgramId");

                    b.ToTable("SegmentData");
                });

            modelBuilder.Entity("HAOS.Models.Training.TrainingProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Subtitle")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ProgramData");
                });

            modelBuilder.Entity("HAOS.Models.Training.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CircuitId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("ExerciseRefId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CircuitId");

                    b.HasIndex("ExerciseRefId");

                    b.ToTable("WorkoutData");
                });

            modelBuilder.Entity("HAOS.Models.Training.Circuit", b =>
                {
                    b.HasOne("HAOS.Models.Training.ProgramDay", null)
                        .WithMany("Circuits")
                        .HasForeignKey("ProgramDayId");
                });

            modelBuilder.Entity("HAOS.Models.Training.ProgramDay", b =>
                {
                    b.HasOne("HAOS.Models.Training.ProgramSegment", null)
                        .WithMany("Days")
                        .HasForeignKey("ProgramSegmentId");
                });

            modelBuilder.Entity("HAOS.Models.Training.ProgramSegment", b =>
                {
                    b.HasOne("HAOS.Models.Training.TrainingProgram", null)
                        .WithMany("Segments")
                        .HasForeignKey("TrainingProgramId");
                });

            modelBuilder.Entity("HAOS.Models.Training.Workout", b =>
                {
                    b.HasOne("HAOS.Models.Training.Circuit", null)
                        .WithMany("Workouts")
                        .HasForeignKey("CircuitId");

                    b.HasOne("HAOS.Models.Training.Exercise", "ExerciseRef")
                        .WithMany()
                        .HasForeignKey("ExerciseRefId");

                    b.Navigation("ExerciseRef");
                });

            modelBuilder.Entity("HAOS.Models.Training.Circuit", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("HAOS.Models.Training.ProgramDay", b =>
                {
                    b.Navigation("Circuits");
                });

            modelBuilder.Entity("HAOS.Models.Training.ProgramSegment", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("HAOS.Models.Training.TrainingProgram", b =>
                {
                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
