// <auto-generated />
using HAOS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HAOS_API.Migrations
{
    [DbContext(typeof(TrainingDb))]
    [Migration("20250623015147_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HAOS.Models.Circuit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProgramDayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProgramDayId");

                    b.ToTable("CircuitData");
                });

            modelBuilder.Entity("HAOS.Models.ProgramDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProgramSegmentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("WeekNum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProgramSegmentId");

                    b.ToTable("ProgramDayData");
                });

            modelBuilder.Entity("HAOS.Models.ProgramSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("TrainingProgramId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainingProgramId");

                    b.ToTable("SegmentData");
                });

            modelBuilder.Entity("HAOS.Models.TrainingProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ProgramData");
                });

            modelBuilder.Entity("HAOS.Models.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CircuitId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RecommendedReps")
                        .HasColumnType("int");

                    b.Property<int>("RecommendedSets")
                        .HasColumnType("int");

                    b.Property<int>("RecommendedWeight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CircuitId");

                    b.ToTable("WorkoutData");
                });

            modelBuilder.Entity("HAOS.Models.Circuit", b =>
                {
                    b.HasOne("HAOS.Models.ProgramDay", null)
                        .WithMany("Circuits")
                        .HasForeignKey("ProgramDayId");
                });

            modelBuilder.Entity("HAOS.Models.ProgramDay", b =>
                {
                    b.HasOne("HAOS.Models.ProgramSegment", null)
                        .WithMany("Days")
                        .HasForeignKey("ProgramSegmentId");
                });

            modelBuilder.Entity("HAOS.Models.ProgramSegment", b =>
                {
                    b.HasOne("HAOS.Models.TrainingProgram", null)
                        .WithMany("Segments")
                        .HasForeignKey("TrainingProgramId");
                });

            modelBuilder.Entity("HAOS.Models.Workout", b =>
                {
                    b.HasOne("HAOS.Models.Circuit", null)
                        .WithMany("Workouts")
                        .HasForeignKey("CircuitId");
                });

            modelBuilder.Entity("HAOS.Models.Circuit", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("HAOS.Models.ProgramDay", b =>
                {
                    b.Navigation("Circuits");
                });

            modelBuilder.Entity("HAOS.Models.ProgramSegment", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("HAOS.Models.TrainingProgram", b =>
                {
                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
